services:
  service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - $PWD:/app
    env_file:
      - local.env
    ports:
      - 8000:8000

  database:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - db_local.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
