services:
  service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - $PWD:/app
    env_file:
      - local-dev-db.env
    ports:
      - 8000:8000
