# Generated by Django 5.1.4 on 2025-01-17 02:49

import django.contrib.postgres.fields
import django.db.models.deletion
import lumberjacked.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='id',
            field=models.PositiveBigIntegerField(default=lumberjacked.utils.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.PositiveBigIntegerField(default=lumberjacked.utils.generate_id, editable=False, primary_key=True, serialize=False)),
                ('movements', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), default=list, size=None)),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
