# Generated by Django 5.1.4 on 2025-01-17 03:07

import django.db.models.deletion
import lumberjacked.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movement_id_workout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.PositiveBigIntegerField(default=lumberjacked.utils.generate_id, editable=False, primary_key=True, serialize=False)),
                ('movement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movement')),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workout')),
            ],
        ),
    ]
