# Generated by Django 5.1.4 on 2025-01-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movementlog_loads_movementlog_notes_movementlog_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlog',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_logs', to='api.workout'),
        ),
    ]
