# Generated by Django 5.1.4 on 2025-01-24 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movementlog_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlog',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movement'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='api.workout'),
        ),
    ]
