# Generated by Django 5.1.4 on 2025-01-24 23:44

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_movementlog_movement_alter_movementlog_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlog',
            name='timestamp',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
