# Generated by Django 5.1.4 on 2025-01-25 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_movementlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementlog',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
