# Generated by Django 5.1.4 on 2025-07-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_movementlog_movement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='recommended_rest_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
