# Generated by Django 5.1.4 on 2025-07-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_movement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
