# Generated by Django 5.1.4 on 2026-06-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_movement_recommended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='body_part',
            field=models.CharField(blank=True, choices=[('full_body', 'Full Body'), ('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('core', 'Core'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('glutes', 'Glutes'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('hip_flexors', 'Hip Flexors'), ('adductors', 'Adductors'), ('abductors', 'Abductors'), ('upper_chest', 'Upper Chest'), ('lower_chest', 'Lower Chest'), ('lats', 'Lats'), ('traps', 'Traps'), ('rhomboids', 'Rhomboids'), ('lower_back', 'Lower Back'), ('front_delts', 'Front Delts'), ('side_delts', 'Side Delts'), ('rear_delts', 'Rear Delts'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('glute_max', 'Glute Max'), ('glute_med', 'Glute Med'), ('gastrocnemius', 'Gastrocnemius'), ('soleus', 'Soleus'), ('rectus_abdominis', 'Rectus Abdominis'), ('obliques', 'Obliques'), ('transverse_abdominis', 'Transverse Abdominis')], max_length=25),
        ),
        migrations.AddField(
            model_name='movement',
            name='resistance_type',
            field=models.CharField(blank=True, choices=[('bodyweight', 'Bodyweight'), ('dumbbell', 'Dumbbell'), ('barbell', 'Barbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('kettlebell', 'Kettlebell'), ('resistance_band', 'Resistance Band'), ('smith_machine', 'Smith Machine'), ('fixed_barbell', 'Fixed Barbell'), ('weighted_vest', 'Weighted Vest'), ('belt_attached', 'Belt-attached'), ('digital', 'Digital'), ('other', 'Other')], max_length=20),
        ),
    ]
