# Generated by Django 5.1.4 on 2026-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_movement_body_part_movement_resistance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='resistance_type',
            field=models.CharField(blank=True, choices=[('bodyweight', 'Bodyweight'), ('dumbbell', 'Dumbbell'), ('barbell', 'Barbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('kettlebell', 'Kettlebell'), ('resistance_band', 'Resistance Band'), ('medicine_ball', 'Medicine Ball'), ('smith_machine', 'Smith Machine'), ('suspension_trx', 'Suspension (TRX)'), ('fixed_barbell', 'Fixed Barbell'), ('weighted_vest', 'Weighted Vest'), ('sandbag', 'Sandbag'), ('belt_attached', 'Belt-attached'), ('digital', 'Digital'), ('other', 'Other')], max_length=20),
        ),
    ]
