# Generated by Django 5.1.4 on 2026-06-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_movement_resistance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='category',
        ),
    ]
