# Generated by Django 5.1.4 on 2026-06-13 21:51

import django.db.models.deletion
import lumberjacked.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_movement_category'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM api_movementlog;"),
        migrations.RemoveField(
            model_name='movementlog',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='movementlog',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='movements',
        ),
        migrations.CreateModel(
            name='WorkoutMovement',
            fields=[
                ('id', models.PositiveBigIntegerField(default=lumberjacked.utils.generate_id, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_movements', to='api.movement')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movementlogtemplate')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_movements', to='api.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='movementlog',
            name='workout_movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movement_log', to='api.workoutmovement'),
        ),
    ]
