# Generated by Django 5.1.4 on 2026-06-14 03:18

import django.db.models.deletion
import lumberjacked.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_movementlog_movement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.PositiveBigIntegerField(default=lumberjacked.utils.generate_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('author', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplateMovement',
            fields=[
                ('id', models.PositiveBigIntegerField(default=lumberjacked.utils.generate_id, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movement')),
                ('movement_log_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movementlogtemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_movements', to='api.workouttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
